version: '3'
services:
  web:
    build:
      nginx
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - "./nginx/html:/html"
      - "./nginx/logs:/logs"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/vhost:/etc/nginx/conf.d"
    links:
      - php
    restart: always
  php:
    build:
      php
    volumes:
      - "./nginx/html:/html"
    working_dir: /html/api.cloud/public
    command: php-fpm
    links:
      - db
    restart: always
  db:
    image: "postgres:10.0-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api.cloud
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8090:8080